### PR TITLE
New feature: Use intro js

### PR DESCRIPTION
**Pull request by viktorsmari**
Don't merge this until someone has verified the Icelandic translations.
(I am unable to switch my local dev setup to icelandic)

Same as #72

### CODE REVIEW

**Comment by bjornlevi** [comment]
perhaps would be cleaner to PR this into a separate branch for testing and then merging?

**Comment by viktorsmari** [comment]
This is a new branch, can you elaborate on 'a separate branch' ?

**Comment by bjornlevi** [comment]
this is a PR into piratar:master - perhaps should be a PR into a dev branch (as a standard). Then you can test it before merging with master.

mostly a question of process really. I'll defer to @BjarniRunar

**Comment by viktorsmari** [comment]
Good idea, can we setup a test/staging server?

**Comment by bjornlevi** [comment]
oh, please. That would be awesome.

**Comment by BjarniRunar** [comment]
Off topic, but: I'm not a fan of staging servers. They're just another thing to admin, with questionable benefits.

The friction we have now has the positive side-effect of keeping the delta between what is live and running, and what the devs are hacking on small. People are wary of making large breaking changes, which is mostly a good thing. Projects with a nice separate dev environment tend to diverge more radically from production, often leading to a vicious cycle of production upgrades becoming more painful, and thus avoided, and thus diverging further and becoming more painful... rather than work on a staging server, I spent time on creating a set of test data to make local testing easier.

Obviously I'm not going to prevent others from setting up a staging server, but I won't be spending time on it myself. :-)

**Comment by 7oi** [comment]
Here I am, almost a year later, checking out this change.

I like it. It might need an update and maybe more instructions, but it's nice and clean, both UX and implementation wise.

**Comment by 7oi** [comment]
Let's just close this one. We'd rather want to see UI improvements later that don't require any instructions for use than instructions like these.

I know you agree with that, @viktorsmari.

**Pull request closed without merging**
