### PR TITLE
WIP: Add vote buttons which move cand to top, bottom

### PR DESCRIPTION
**Pull request by viktorsmari**
- Added buttons which move candidates to top and bottom.
- Small jQuery and CSS refactoring

Note: do not merge yet, the freeze/pin button does nothing at the moment.
Also, need to move the candidate number CSS wise.

I am not sure if the arrows are intuitive enough, I was searching for a 'double up/down' arrows but could not find any. However I found them in another library, font awesome. Should we add that as a dependency as well? (I am not a fan of adding to many libraries)
They look like this:
http://fontawesome.io/icon/angle-double-up/

Compare it with the screenshot:
2016-08-05_563x585

Test if you feel like it and comment!

### CODE REVIEW

**Comment by viktorsmari** [comment]
Here is a list of icons in the library we are currently using, if you find something more appropriate:
http://getbootstrap.com/components/

**Comment by viktorsmari** [comment]
And here is an idea of what could happen if you 'pin / freeze' someone:

2016-08-05_528x561

**Comment by BjarniRunar** [comment]
This looks like a great start!

Main concerns: Can we reduce the margins a bit to make more space for the name? I'm a little uncomfortable with the pin and the X being so close to each other. Could we arrange like this: pin, top/bot, up/down, x ? Or does the layout just become a major PITA?

It's too bad the fast-forward and fast-backward icons from that icon set don't have versions rotated 90 degrees. Can we rotate things 90 degrees with CSS? Is that too crazy? Or just do it by hand and ship a couple of pngs maybe?

**Comment by BjarniRunar** [comment]
In the frozen version, the pin button needs to still be available for unpinning. And I think greying out the name might be sending the wrong message - pinning someone is an awesome thing, not something that makes them "less important".

Hope I'm not too nitpicky, I'm thrilled you're working on this. :-)

**Comment by BjarniRunar** [comment]
Maybe instead of the pin, the glyph icons for "check" and "edit" could alternate? So you check someone when they're in the right place, but click edit to make them movable again.

**Comment by BjarniRunar** [comment]
Also I noticed little fingers pointing up and down. Maybe they're good for send-to-top and send-to-bottom.

Sorry too many comments excited yay.

**Comment by BjarniRunar** [comment]
And actually, to reduce visual clutter, in the pinned (checked?) mode, the buttons may as well just disappear entirely, except for the lone button which unpins. That also suggests moving the pinning button somewhere else entirely, possibly underneath the number?

OK, I'll stop now.

**Comment by viktorsmari** [comment]
Why didn't I think of the rotate 90 deg? DERP! :smile: 

I think the first one looks a bit better:
2016-08-06_273x90

The second one is a bit noisy IMO but maybe it makes more sense for other people?:
2016-08-06_222x90

And now when you freeze someone, the toggling works and buttons are disabled:
2016-08-06_345x189

I think we might need two buttons with more difference between them, the edit and check might look to similar?

**Comment by viktorsmari** [comment]
Current update:

Freeze has been disabled, so we might even put this in production if tests are ok.

2016-08-06_435x384

**Comment by BjarniRunar** [comment]
I'd be happy to merge this and even deploy, except you made the Remove button disappear which means the page will look surprisingly different and won't match the videos and teaching materials which have been prepped for the elections. I think we can get away with adding a single button, but removing things at this stage seems unwise.

Can you move the bring back the X button? Perhaps arrange them like so?  [...] [up] [dn] [x]

**Comment by viktorsmari** [comment]
Good idea, however ordering is the following so the [X] button won't appear underneath the [up] on mobiles, see screenshots.

**Desktop**:
2016-08-09_1086x489


 **Mobile**, (iPhone 6 sizes), notice the line break on the buttons:
2016-08-09_409x322

**Comment by 7oi** [comment]
So, where's this at? Is everyone on board for this, in spite of the button ordering on mobiles?

**Pull request merged**
