### PR TITLE
WIP: Add basic selenium tests.

### PR DESCRIPTION
**Pull request by viktorsmari**
This will:
* check the homepage for some CSS classes and a page title
* create a user  - **needs the user not to exist -> a clean db**
* try to log you in (email verification required)

The following is still needed:
- [ ] Configure Travis `.travis.yml` to run the tests.
- [ ] It seems the database is not deleted between runs? It needs a clean db to register a new user.
- [ ] Locally, you **need** to have the server running before running the tests. Maybe the test should start a server?

### CODE REVIEW

**Comment by viktorsmari** [comment]
I put the tests.py file in `wasa2il/tests.py` - Feel free to move it elsewhere.

Run it with:
`./manage.py test wasa2il`

But you need *geckodriver* https://github.com/mozilla/geckodriver/releases in `/usr/local/bin`

Also *selenium* is needed:
 `pip install selenium`

Is there a way in Django to have dependencies only for development environment? Rails does this but I am new to Django. Because Selenium won't be needed for the production server, I was reluctant to add it to the requirements.txt.

**Comment by helgihg** [comment]
I don't mind Selenium being a requirement for a production environment, seeing that it's required for testing purposes. So I wouldn't mind it being included in the general requirements file. What do you think, @smari ?

**Comment by viktorsmari** [comment]
The final objective was to have a 'front end' test. A test that clicks around and does stuff.
This is still a 'work in progress' (WIP) - so I was hoping someone motivated would continue the work.
Feel free to delete it if it is in your way ;)

**Comment by helgihg** [comment]
@viktorsmari Okay, cool, I'll close it for now, but feel free to re-open or re-submit when you feel it's appropriate. :) Thanks for your efforts, they are most surely appreciated!

**Pull request closed without merging**
