### PR TITLE
Ui votes updown buttons - WIP, feedback welcome

### PR DESCRIPTION
**Pull request by viktorsmari**
This is still a work in progress, need to tweak the user names. Maybe put them in a separate line.

The voting looks like this currently:

2016-06-17_523x458

### CODE REVIEW

**Comment by viktorsmari** [comment]
Current state works fine on mobile: 

2016-06-17_523x452

**Comment by bjornlevi** [comment]
I like this.

This is both moving candidates and thumbnail for commenters?

I'll defer merging this to @BjarniRunar

**Comment by viktorsmari** [comment]
@bjornlevi : I don't understand, moving 'thumbnail for commenters' ?
Are there any comments on this page?

He who will merge this should of course test this feature to be on the safe side :)

**Comment by bjornlevi** [comment]
see changes to: wasa2il/templates/core/topic_detail.html

**Comment by viktorsmari** [comment]
Ahh I see, I often forget to branch out from master before I start working on a new branch.
I removed that change :)

**Comment by BjarniRunar** [comment]
Awesome, thanks for doing this! Merging, will test at my end before updating the live system.

**Pull request merged**
