### PR TITLE
Fix .po file generation

### PR DESCRIPTION
**Pull request by nifgraup**
This commit replaces two of Django's management commands, makemessages and compilemessages with Python based implementations. Makemessages now scans wasa2il related files and skips the ones in virtualenv.

Updated readme to guide contributors who modify strings.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
Can you explain what problem you are solving? Why are the django default commands inadequate?

**Comment by viktorsmari** [comment]
I am just guessing but does this have anything to do with this for example?

2016-08-19_653x341

This is when I push a commit after having done some translations in my venv (virtualenv).

**Comment by nifgraup** [comment]
The reason is twofold:

1. Fix makemessages to get rid of unrelated strings picked up from the venv folder. It will be easier for translators to do their work when the message catalog only contains relevant strings.
2. Simplify installation by not having to install gettext separately. Especially relevant for Mac OS X and Windows.

**Comment by 7oi** [comment]
I've tested this out and I like it. It's neat and behaves nicely and the reasoning behind it is, well, reasonable.

Due to merge conflicts I'll be doing the merge locally and pushing straight to development.

**Pull request merged**
