### PR TITLE
Makefile easy install

### PR DESCRIPTION
**Pull request by steinnes**
Since some people mentioned in issue #25 that getting the project setup was problematic for them I decided to attempt setting it up locally and then see if I could make it easier.  Setting it up was no problem for me, but maybe having more details in the README + the easy to use make targets will help some people.

~~The make targets have only been tested on OS X, but I'l try them out on one of my Linux boxes in a few minutes.~~. Tested on Linux too now see first comment.

I think we could make the Dockerfile more useful too, what I've usually done in the past is written make commands which build the dockers for me and tag them with the current githash, using git-archive to create them.  That's not really convenient for development though, but for me dockers are something I use for CI / production artifacts/deliverables, so I'm not an expert on making them nice for development :-)

### CODE REVIEW

**Comment by steinnes** [comment]
Runs on Linux now too.  Had to add a switch to `initial_setup.py` which rather crudely ties it and the `venv` assumption from the Makefile together.

**Comment by helgihg** [comment]
This seems like doing the same thing twice to me (and I only use Linux). The script initial_setup.py is intended as an OS-agnostic setup script that works just as well for Linux as anything else, and should much rather handle these things if so intended. It already installs Python packages from requirements.txt, and when we designed it, we made the consicous choice of leaving it to users themselves whether they wish to use virtualenv. If we want to make virtualenv the default option, it should much rather reside in initial_setup.py.

Also adding a Makefile adds another requirement (or obfuscation, either way) in that it requires 'make' which is usually not installed by default. Python however is installed by default on almost any OS, including bare-bones Debian.

**Comment by gakera** [comment]
I think that a better strategy is to adjust the Dockerfile to make portability easier. Currently the Dockerfile works great on Linux and OSX and I'm checking if the changes I made to get it working on Windows affect the other systems before I commit the changes. 

I've already made Docker instructions, which can be added to the readme or wiki or whatever, after a little polish: https://workflowy.com/#/0e135cce3863

**Comment by gakera** [comment]
Then again, having a make file could be great if that means more people are willing to try to set up the system and use / develop it. As long as the make file is kept up to date and its implementation doesn't interfere with other ways of getting the system up and running, I think it would be ok to include it.

**Comment by steinnes** [comment]
Thanks for the comments guys, I appreciate them.  The makefile is just something I've used nicely on many occasions to package small python projects to make it easy to develop them locally with virtualenvs, etc.  Not going to try and force my preferences on your project :-)

I didn't want to make too many changes to the setup script itself, as I probably would have done the installation executed there completely in a Makefile, so the comment from @helgihg is very valid: there are now two "setup" scripts, although we know the Makefile is just like a collection of helper bash scripts, to a newcomer it might be confusing.

If we would drop the Makefile and rewrite the README sections to just explain the commands being executed, would you think this is a worthwhile addition?

**Comment by gakera** [comment]
That would be very helpful. I would also like to keep the section about the Docker setup, since the Dockerfile is an old addition to the project, it deserves some explanation. I'm just getting started with Docker myself, I did not create the Dockerfile.

**Comment by steinnes** [comment]
I'll do that.  If you want help with improving the "dockerization" of this project I'd be glad to assist, I consider myself a little bit of an expert, although I haven't used the latest couple of versions.

If more people are interested in learning about Docker, here's a little tutorial / instruction post I wrote for a workshop at my previous job, I try to do a good job of explaining them from a very "practical" standpoint, in the hopes people get quickly off the ground.  http://steinn.org/post/docker-workshop/

**Comment by gakera** [comment]
Fantastic! I'll look at that when I get home and when I have a chance to verify that my addition to the Dockerfile does not interfere with other OSes, I will commit it and issue a pull request. 

What we would very much like is a Docker container that can more easily be reused, as it is now we have to build a new container each time we make changes to the python code. And I'm not sure I'm able to stop the container and start it up again, I think you have to re-build it each time. 

We've been discussing these options in the Slack chat https://piratar.slack.com/ and you're welcome to join.

**Comment by bjornlevi** [comment]
There are conflicts between master and branch now, Fix the conflicts in the branch and pull request again please.

**Pull request closed without merging**
