### PR TITLE
help templates: fix file existance check and use template files in Icelandic as a fallback

### PR DESCRIPTION
**Pull request by nifgraup**

### CODE REVIEW

**Comment by kjwise** [comment]
Initial setup should be runnable before you have django installed.

**Comment by bjornlevi** [comment]
it is, pip install is still in there

**Comment by nifgraup** [comment]
@kjwise I see, that explains the copy of get_random_string. I didn't come across that because the Dockerfile runs pip install before initial_setup.py (I'll remove that bit).

**Comment by kjwise** [comment]
Initial setup needs to be runnable by non docker using users

**Comment by nifgraup** [comment]
Understand, that's what I'm going for. 8f4be7f should be reverted.

**Pull request merged**
