### PR TITLE
Ability to change proposals before they're put to a vote

### PR DESCRIPTION
**Pull request by helgihg**

### CODE REVIEW

**Comment by bjornlevi** [comment]
my mistake here, I thought I could choose which branch to merge the pull request into but it's the pull requester that makes that choice. It would be appropriate to have a development branch to merge into and test and use the master branch only for deployments.

I'll create a development branch to receive pull requests - make a new one for that branch please :)

**Comment by helgihg** [comment]
Normally I'd agree, but the fact of the matter is that we don't have a
development setup, nor a testing team, but we do however need rather
quick roll-outs of improvements. The way I see it, we should just use
the master branch. Otherwise I fear stagnation of the main instance.

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by helgihg** [comment]
Also consider that the software is still essentially in beta.

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by bjornlevi** [comment]
Doesn't mean we shouldn't do things "properly" :)

By having a development branch we can merge, test (on dev) and then deploy to master. It's only like the "basic" way of doing multi user code maintenance.

**Comment by helgihg** [comment]
Fair enough.

But then who takes care of that procedure? Where is it tested and by whom?

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by bjornlevi** [comment]
By whoever does the merge. I guess I am setting myself up as the self appointed default.

**Comment by helgihg** [comment]
Good stuff. ;)

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Pull request closed without merging**
