### PR TITLE
Add Heroku to ALLOWED_HOSTS for development

### PR DESCRIPTION
**Pull request by viktorsmari**
So this website can work:
https://wasa2il-development.herokuapp.com/

This is automatically built whenever a new branch to development is pushed.

### CODE REVIEW

**Comment by viktorsmari** [comment]
This is a super useful feature @7oi implemented, but is broken atm.
Maybe this is not the best way to do it, what you you think @helgihg @smari ?

**Comment by helgihg** [comment]
Haven't used Heroku myself, but I'm told it's super awesome. The one problem I have with pulling in the request is that it breaks the Travis CI build. Can you fix it?

**Comment by viktorsmari** [comment]
I think there is a missing configuration on Travis, it seems to lack the **CODACY_PROJECT_TOKEN** for branches other then 'master' and 'development'
When I run the `script` section of `.travis.yml` locally I get:
> ERROR - environment variable CODACY_PROJECT_TOKEN is not defined.

**Comment by 7oi** [comment]
I believe I have fixed the problem with the CODACY_PROJECT_TOKEN. This PR seem legit, I'm gonna merge it.

**Pull request merged**
