### PR TITLE
Merge in latest work: ballot truncation, test data, bugfixes

### PR DESCRIPTION
**Pull request by BjarniRunar**
This PR brings the following new things:

   * A script (manage.py load_fake_data) which populates the DB with fake data
   * Adaptive ballot truncation in core/elections.py, for anonymizing published ballots
   * Helper functions for testing membership, getting voter lists, things like that

It should also fix a couple of bugs and improve performance by avoiding the "user in polity.members.all()" pattern which will load the entire user list every single time it ran (often many times per query, see https://docs.djangoproject.com/en/1.9/ref/models/querysets/#django.db.models.query.QuerySet.exists). Googling the docs shows I should have used exists() instead of count(), but hey, there's always room for improvement...

### CODE REVIEW

**Comment by BjarniRunar** [comment]
I'll just leave this here for a while in case anyone wants to take a look and comment... :-)

**Comment by viktorsmari** [comment]
Maybe add to the readme, the users login info (user, pass if there are users) and how to import the data.

**Comment by BjarniRunar** [comment]
@viktorsmari Good point. Done in latest commit. :-)

**Comment by BjarniRunar** [comment]
I'm going to merge this, so folks can give it a try and give feedback. I'll start another running PR for ongoing work.

**Pull request merged**
