### PR TITLE
Single settings file, using ENV vars

### PR DESCRIPTION
**Pull request by viktorsmari**
Working on #212

### CODE REVIEW

**Comment by helgihg** [comment]
@viktorsmari I don't have a strong opinion on it. I'd choose MySQL just because that's what the only known production setup uses. Also *I guess* more people are already familiar with MySQL than Postgresql. I readily accept these not being particularly strong arguments, but that's why I don't really have a strong opinion on it. :) I wouldn't protest either way.

**Comment by viktorsmari** [comment]
This PR is ready, it would be nice if someone would review it :)
It needs to be tested running 'normally' **and** using Docker

To use Docker, follow the README or do
`git checkout single-settings-file`
`docker-compose up`
If **mysql** container has not started in time, resulting in a Django error, do `docker-compose restart wasaweb`

Visit http://localhost:8000

**Comment by viktorsmari** [comment]
For non-docker environments, we can add this package, which also reads a `.env` file.
https://github.com/joke2k/django-environ

That means in non-docker production environment you edit a `.env` with all the secrets, **which is gitignored,** instead of having to write them in the settings file, or exposing them on the host OS env vars

**Comment by smari** [comment]
Merging this after talking with @viktorsmari; I think this is a step forward. It may require some fiddling with their .env for those who have a nice setup at the moment, but it's time to cross that Rubicon.

**Pull request merged**
