### PR TITLE
An entry page for all of users polities

### PR DESCRIPTION
**Pull request by baldurjonsson**
Hi there,
My take on a _frontpage_ for _wasa2il_
If you have feedback, please do.

As is, the new view is shown if there's no front polity
Much related issue: #107 
It's unwise to merge until #93 is closed.

image

### CODE REVIEW

**Comment by baldurjonsson** [comment]
Also, missing translation.

**Comment by BjarniRunar** [comment]
This is great!

Quick question: Why are you separating the elections that are voting from the elections that are soliciting candidates? It seems there will rarely be so many of them...?

**Comment by baldurjonsson** [comment]
Great question, hadn't really thought about it. I will make it so.

I also had a thought take make elections on top if there are any open for voting, if only open for candidates or none at all make issues on top. Haven't figured out the best way to do it though

**Comment by baldurjonsson** [comment]
Did a little rework on the layout per @BjarniRunar 's suggestion.

image

**Comment by BjarniRunar** [comment]
I like this, it's useful and I strongly suspect it should replace our current front page.

However, before that's decided we'll need to get some live feedback without replacing the current setup - which is actually impossible since there's no way to trigger this view without disabling the "front polity", which is a surprising change which we can't really launch right in the middle of elections.

How about moving this into the /polities/ overview page? Maybe just leave the list of all polities at the bottom of the page, put add this at the top? We could then deploy that, it'd be immediately useful and visible when people click the logo, and we can get some feedback before pulling the trigger and disabling the front polity.

**Comment by BjarniRunar** [comment]
Also, quick question: what does it display if the user is not logged in?

**Comment by baldurjonsson** [comment]
@BjarniRunar when not authenticated it lists all polities which are nonmember readable.
Regarding the _/polities/_ idea, I like it. I'll do that when I get home tonight.

**Comment by baldurjonsson** [comment]
Added the summary to the polities route, left other functionality as is.
As long as _front_polity_ is True the main route will stay the same. :)

**Pull request merged**
